services:
  postgres:
    image: postgres:13-alpine
    container_name: pga_container
    environment:
      - POSTGRES_DB=my-bus-map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/pga/data
    restart: always

volumes:
    postgres-data:
